variables:
  RunNumber: '$(Build.BuildNumber)'

parameters:
  - name: onlyDeploy
    default: false
    type: boolean

  - name: environment
    displayName: Environment
    type: string
    default: dev

  - name: deployBuildNumber
    default: latest
    type: string

trigger:
- manual

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  condition: eq('${{ parameters.onlyDeploy }}', false)
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'acrblendnet${{ parameters.environment }}'
    - task: CmdLine@2
      inputs:
        script: 'sed -i ''s|kv-blendnet-dev|kv-blendnet-${{ parameters.environment }}|g'' blendnet.retailer.api/appsettings.json'
    - task: CmdLine@2
      displayName: "Building docker image"
      inputs:
        script: "docker build -t acrblendnet${{ parameters.environment }}.azurecr.io/blendnet.retailer.api:$(RunNumber) -f ./blendnet.retailer.api/Dockerfile ."

    - task: CmdLine@2
      displayName: "Pushing image to ACR"
      inputs:
        script: "docker push acrblendnet${{ parameters.environment }}.azurecr.io/blendnet.retailer.api:$(RunNumber)"

    - task: Docker@2
      displayName: Logout of ACR
      inputs:
        command: logout
        containerRegistry: 'acrblendnet${{ parameters.environment }}'

- stage: Deploy
  dependsOn: Build
  condition: or(succeeded(), eq('${{ parameters.onlyDeploy }}', true))
  jobs:
  - job: Deploy
    steps:
    - task: CmdLine@2
      condition: eq('${{ parameters.onlyDeploy }}', false)
      inputs:
        script: 'sed -i ''s|image_name|acrblendnet${{ parameters.environment }}.azurecr.io/blendnet.retailer.api:$(RunNumber)|g'' blendnet.retailer.api/blendnet.retailer.api.yaml'
    - task: CmdLine@2
      condition: eq('${{ parameters.onlyDeploy }}', true)
      inputs:
        script: 'sed -i ''s|image_name|acrblendnet${{ parameters.environment }}.azurecr.io/blendnet.retailer.api:${{ parameters.deployBuildNumber }}|g'' blendnet.retailer.api/blendnet.retailer.api.yaml'
    - task: CmdLine@2
      inputs:
        script: 'sed -i ''s|pod_identity_name|blendnet-${{ parameters.environment }}-pod-identity|g'' blendnet.retailer.api/blendnet.retailer.api.yaml'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-blendnet-${{ parameters.environment }}-default'
        manifests: 'blendnet.retailer.api/blendnet.retailer.api.yaml'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-blendnet-${{ parameters.environment }}-default'
        manifests: 'appgateway.yaml'
