apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blendnet-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /cms/*
        backend:
          serviceName: blendnet-cms-api
          servicePort: 80