trigger:
- manual

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-blendnet-dev-default'
    manifests: 'appgateway.yaml'
