apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blendnet-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: blendnetcert
spec:
  rules:
  - http:
      paths:
      - path: /cmsapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-cms-api
            port: 
              number: 5000
      - path: /userapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-user-api
            port: 
              number: 5000
      - path: /retailerapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-retailer-api
            port: 
              number: 5000
      - path: /omsapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-oms-api
            port: 
              number: 5000
      - path: /portal/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-cms-web-ui
            port: 
              number: 5000
      - path: /incentiveapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-incentive-api
            port: 
              number: 5000
      - path: /notificationapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-notification-api
            port: 
              number: 5000
      - path: /deviceapi/*
        pathType: Prefix
        backend:
          service:
            name: blendnet-device-api
            port: 
              number: 5000
