apiVersion: apps/v1
kind: Deployment
metadata:
  name: blendnet-retailer-listener
  labels:
    app: blendnet-retailer-listener
spec:
  replicas: pod_count
  selector:
    matchLabels:
      app: blendnet-retailer-listener
  template:
    metadata:
      labels:
        app: blendnet-retailer-listener
        aadpodidbinding: pod_identity_name
    spec:
      containers:
      - name: blendnet-retailer-listener
        image: image_name
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 80