export enum ContentStatus {
    UNPROCESSED = 'UNPROCESSED',
    PROCESSING = 'PROCESSING',
    PROCESSED = 'PROCESSED',
    BROADCASTING = 'BROADCASTING',
    ARCHIVED = 'ARCHIVED',
    ARCHIVING = 'ARCHIVING',
    DELETING = 'DELETING',
    BROADCASTED = 'BROADCASTED',
    REVOKE = 'REVOKE'
}
