# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- manual

pool:
  vmImage: ubuntu-latest

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     cd blendnet.cms.web.ui
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(acr-service-connection)

- task: CmdLine@2
  displayName: "Building docker image"
  inputs:
    script: "docker build -t $(image_name):$(RunNumber) -f ./blendnet.cms.web.ui/Dockerfile ."

- task: CmdLine@2
  displayName: "Tagging docker image"
  inputs:
    script: "docker tag $(image_name):$(RunNumber) $(image_name):latest"

- task: CmdLine@2
  displayName: "Pushing image to ACR"
  inputs:
    script: "docker push --all-tags $(image_name)"

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: $(acr-service-connection)

