apiVersion: apps/v1
kind: Deployment
metadata:
  name: blendnet-cms-web-ui
  labels:
    app: blendnet-cms-web-ui
spec:
  replicas: pod_count
  selector:
    matchLabels:
      app: blendnet-cms-web-ui
  template:
    metadata:
      labels:
        app: blendnet-cms-web-ui
        aadpodidbinding: pod_identity_name
    spec:
      containers:
      - name: blendnet-cms-web-ui
        image: image_name
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 3
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: blendnet-cms-web-ui
spec:
  ports:
  - port: 5000
    targetPort : 5000
  selector:
    app: blendnet-cms-web-ui
