FROM cblmariner.azurecr.io/base/core:1.0 as build-web
RUN tdnf -y install nodejs
ENV NODE_OPTIONS=--tls-cipher-list='ECDHE-RSA-AES128-GCM-SHA256:!RC4'

WORKDIR /app

COPY blendnet.cms.web.ui /app
RUN npm install
RUN npm run build-dev
